---
format: 
  clean-revealjs:
    footer: "PGE Undergraduate Studies Committee Meeting"
    scrollable: true
execute:
  freeze: true
title: "PGE Undergraduate Studies Committee Meeting"
author: 
  - name: John T. Foster (Chair)
    email: john.foster@utexas.edu
date: January 24, 2024
---

## Agenda

* "Industry Software" Training

* PGE BS / McCombs BA Dual Degree

* Review and updating of the approved elective courses list

## "Industry Software" Training

 * Supported by EAC and student leaders
 * How to offer?
   * Voluntary registration and attendance
   * Elective course
     * Full or half day Fridays? Other formats?
     * Cockrell School approval?
     * Who teaches?
 * Action Items?

::: {.fragment}
### Potential Vendors

  1. ComboCurve, (Douglas McMaster doug.j.mcmaster@gmail.com)
  2. Spotfire (Bryan McDowell bryan.mcdowell@sabata.us)
  3. ARIES, QED (Courtney Stephens cstephens@QEDea.com)
  4. Whitson (Mathias Carlsen carlsen@whitson.com)
  5. KAPPA (Vincent Artus, artus@kappaeng.com and Irina Kostyleva, kostyleva@kappaeng.com)
  6. NSI (Dante Guerra; dguerra@nsitech.com)
  7. Harmony/S&P Global (Alireza, alireza.haghighat@spglobal.com)
  8. ResFrac (Mark McClure)
  9. Unconventional Reservoir Engineering (Yoshi, Yogashri Umesh Pradhan
  ypradhan.pge@utexas.edu)
  10. Enverus 
  11. PhDWin
:::

## PGE BS / McCombs BA Dual Degree

 * Is this a good idea?
   * Budget Council and Dept. Chair are enthusiastic
 * ECE/McCombs Honors Program - [https://ecb.utexas.edu/](https://ecb.utexas.edu/)
   * Does it have to be honors?
 * Action Items?
   * Draft cirriculum
   * Setup meeting with McCombs


## Review and Update PGE approved electives 

 * [Current list](https://www.pge.utexas.edu/sites/default/files/PDFs/Undergraduate/Approved%20Electives%20List.pdf)
